##
# Local development override for docker-compose.yml.
#
# This file overrides docker-compose.yml with local development practices aimed
# at non-Linux systems.
#
# Overrides:
# Replaces the standard volume mount that shares code into the Docker
# container with the Outrigger unison filesystem sync.
#
# Run 'rig project sync' to start syncing.
# @see http://docs.outrigger.sh/project-setup/filesystem-sync/
#
# This configuration is automatically applied when you use the implicit default
# docker-compose.yml configuration file (e.g., when you **do not** specify the
# -f flag.)
#
# To skip including this configuration, run 'docker-compose -f docker-compose.yml ...'
##
version: '3.3'

services:
  www:
    volumes:
      - drupal8-sync:/var/www

volumes:
  drupal8-sync:
    external: true
