##
# Build and command-line operations containers for your local environment.
#
# @see https://docs.docker.com/compose/reference/overview/
# @see https://docs.docker.com/compose/compose-file/compose-file-v2/
##
version: '3.2'

services:
  cli:
    image: outrigger/build:php71
    network_mode: "bridge"
    entrypoint: [ "/init" ]
    working_dir: /var/www
    command: /bin/bash
    environment:
    volumes:
      - .:/var/www/html
      - /data/uv/files:/var/www/html/files-in-data
      - uv-sync:/var/www/html/files-via-unison
volumes:
  uv-sync:
    external: true
